// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        data_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_ce
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] data_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;
output  [15:0] ap_return_32;
output  [15:0] ap_return_33;
output  [15:0] ap_return_34;
output  [15:0] ap_return_35;
output  [15:0] ap_return_36;
output  [15:0] ap_return_37;
output  [15:0] ap_return_38;
output  [15:0] ap_return_39;
output  [15:0] ap_return_40;
output  [15:0] ap_return_41;
output  [15:0] ap_return_42;
output  [15:0] ap_return_43;
output  [15:0] ap_return_44;
output  [15:0] ap_return_45;
output  [15:0] ap_return_46;
output  [15:0] ap_return_47;
output  [15:0] ap_return_48;
output  [15:0] ap_return_49;
output  [15:0] ap_return_50;
output  [15:0] ap_return_51;
output  [15:0] ap_return_52;
output  [15:0] ap_return_53;
output  [15:0] ap_return_54;
output  [15:0] ap_return_55;
output  [15:0] ap_return_56;
output  [15:0] ap_return_57;
output  [15:0] ap_return_58;
input   ap_ce;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] grp_fu_1522_p4;
reg   [15:0] reg_1622;
wire    ap_CS_fsm_state2;
wire   [15:0] grp_fu_1542_p4;
reg   [15:0] reg_1626;
wire    ap_CS_fsm_state8;
wire   [15:0] grp_fu_1552_p4;
reg   [15:0] reg_1630;
wire    ap_CS_fsm_state10;
wire   [15:0] grp_fu_1572_p4;
reg   [15:0] reg_1634;
wire    ap_CS_fsm_state6;
wire   [15:0] grp_fu_1592_p4;
reg   [15:0] reg_1638;
reg   [15:0] reg_1642;
reg   [15:0] reg_1646;
wire    ap_CS_fsm_state7;
wire   [15:0] grp_fu_1582_p4;
reg   [15:0] reg_1650;
reg   [14:0] reg_1654;
wire    ap_CS_fsm_state3;
reg   [15:0] reg_1658;
wire    ap_CS_fsm_state5;
reg   [15:0] reg_1662;
reg   [15:0] reg_1666;
wire    ap_CS_fsm_state9;
wire  signed [15:0] trunc_ln203_fu_1670_p1;
reg  signed [15:0] trunc_ln203_reg_2877;
wire  signed [25:0] sext_ln1118_60_fu_1674_p1;
reg  signed [25:0] sext_ln1118_60_reg_2884;
wire   [15:0] grp_fu_1532_p4;
reg   [15:0] mult_17_V_reg_2894;
reg   [15:0] mult_30_V_reg_2899;
reg   [15:0] mult_40_V_reg_2904;
reg  signed [15:0] tmp_1_reg_2909;
reg  signed [15:0] tmp_2_reg_2918;
reg  signed [15:0] tmp_3_reg_2925;
reg   [13:0] trunc_ln_reg_2933;
reg   [15:0] mult_79_V_reg_2938;
reg   [15:0] mult_82_V_reg_2943;
reg   [13:0] tmp_reg_2948;
wire  signed [24:0] sext_ln1118_64_fu_1768_p1;
reg  signed [24:0] sext_ln1118_64_reg_2953;
wire   [15:0] add_ln703_83_fu_1792_p2;
reg   [15:0] add_ln703_83_reg_2961;
wire  signed [25:0] sext_ln1118_63_fu_1798_p1;
reg  signed [25:0] sext_ln1118_63_reg_2966;
reg   [15:0] mult_146_V_reg_2975;
reg   [15:0] mult_147_V_reg_2980;
reg   [15:0] mult_151_V_reg_2985;
reg   [15:0] mult_152_V_reg_2990;
reg   [15:0] mult_154_V_reg_2995;
reg   [15:0] mult_185_V_reg_3000;
wire    ap_CS_fsm_state4;
reg   [15:0] mult_191_V_reg_3005;
wire   [14:0] grp_fu_1612_p4;
reg   [14:0] trunc_ln708_2_reg_3010;
reg   [15:0] mult_219_V_reg_3015;
reg   [15:0] mult_231_V_reg_3020;
reg   [14:0] trunc_ln708_3_reg_3025;
wire  signed [25:0] sext_ln1118_68_fu_1818_p1;
reg  signed [25:0] sext_ln1118_68_reg_3030;
reg   [15:0] mult_258_V_reg_3042;
wire   [15:0] acc_83_V_fu_1876_p2;
reg   [15:0] acc_83_V_reg_3047;
reg   [15:0] mult_264_V_reg_3052;
reg   [15:0] mult_266_V_reg_3058;
reg   [15:0] mult_275_V_reg_3063;
reg   [15:0] mult_290_V_reg_3068;
wire   [15:0] acc_29_V_fu_1888_p2;
reg   [15:0] acc_29_V_reg_3074;
wire   [15:0] acc_35_V_fu_1906_p2;
reg   [15:0] acc_35_V_reg_3079;
reg   [15:0] mult_304_V_reg_3084;
reg   [15:0] mult_309_V_reg_3089;
reg   [15:0] mult_312_V_reg_3094;
reg   [15:0] mult_318_V_reg_3099;
reg   [15:0] mult_323_V_reg_3104;
reg   [15:0] mult_331_V_reg_3109;
reg   [14:0] trunc_ln708_8_reg_3114;
reg   [14:0] trunc_ln708_1_reg_3119;
reg   [15:0] mult_363_V_reg_3124;
wire  signed [24:0] sext_ln1118_71_fu_2009_p1;
reg  signed [24:0] sext_ln1118_71_reg_3129;
wire  signed [25:0] sext_ln1118_72_fu_2013_p1;
reg  signed [25:0] sext_ln1118_72_reg_3134;
reg   [15:0] mult_389_V_reg_3146;
wire   [15:0] acc_6_V_fu_2077_p2;
reg   [15:0] acc_6_V_reg_3151;
wire   [15:0] acc_27_V_fu_2089_p2;
reg   [15:0] acc_27_V_reg_3156;
wire   [15:0] acc_102_V_fu_2101_p2;
reg   [15:0] acc_102_V_reg_3161;
wire   [15:0] acc_103_V_fu_2118_p2;
reg   [15:0] acc_103_V_reg_3166;
wire   [15:0] acc_125_V_fu_2130_p2;
reg   [15:0] acc_125_V_reg_3171;
reg   [15:0] mult_392_V_reg_3176;
reg   [15:0] mult_398_V_reg_3181;
reg   [15:0] mult_405_V_reg_3186;
reg   [15:0] mult_426_V_reg_3191;
wire   [15:0] acc_19_V_fu_2152_p2;
reg   [15:0] acc_19_V_reg_3196;
wire   [15:0] acc_26_V_fu_2169_p2;
reg   [15:0] acc_26_V_reg_3201;
wire   [15:0] acc_45_V_fu_2181_p2;
reg   [15:0] acc_45_V_reg_3206;
wire   [15:0] acc_48_V_fu_2196_p2;
reg   [15:0] acc_48_V_reg_3211;
wire   [15:0] acc_53_V_fu_2207_p2;
reg   [15:0] acc_53_V_reg_3216;
wire   [15:0] acc_54_V_fu_2218_p2;
reg   [15:0] acc_54_V_reg_3221;
wire   [15:0] acc_62_V_fu_2230_p2;
reg   [15:0] acc_62_V_reg_3226;
wire   [15:0] acc_63_V_fu_2246_p2;
reg   [15:0] acc_63_V_reg_3231;
wire   [15:0] acc_64_V_fu_2258_p2;
reg   [15:0] acc_64_V_reg_3236;
wire   [15:0] acc_67_V_fu_2270_p2;
reg   [15:0] acc_67_V_reg_3241;
wire   [15:0] acc_8_V_fu_2283_p2;
reg   [15:0] acc_8_V_reg_3246;
wire   [15:0] acc_73_V_fu_2294_p2;
reg   [15:0] acc_73_V_reg_3251;
wire   [15:0] acc_75_V_fu_2306_p2;
reg   [15:0] acc_75_V_reg_3256;
wire   [15:0] acc_87_V_fu_2317_p2;
reg   [15:0] acc_87_V_reg_3261;
wire   [15:0] acc_93_V_fu_2328_p2;
reg   [15:0] acc_93_V_reg_3266;
reg  signed [10:0] grp_fu_336_p0;
reg  signed [15:0] grp_fu_336_p1;
wire  signed [23:0] sext_ln1118_fu_1716_p1;
reg  signed [10:0] grp_fu_337_p0;
reg  signed [15:0] grp_fu_337_p1;
reg  signed [10:0] grp_fu_338_p0;
reg  signed [15:0] grp_fu_338_p1;
reg  signed [10:0] grp_fu_339_p0;
reg  signed [15:0] grp_fu_339_p1;
wire    ap_CS_fsm_state11;
reg  signed [10:0] grp_fu_340_p0;
reg  signed [15:0] grp_fu_340_p1;
reg  signed [10:0] grp_fu_341_p0;
reg  signed [15:0] grp_fu_341_p1;
reg  signed [10:0] grp_fu_342_p0;
reg  signed [15:0] grp_fu_342_p1;
reg  signed [10:0] grp_fu_343_p0;
reg  signed [15:0] grp_fu_343_p1;
wire   [25:0] grp_fu_343_p2;
wire   [25:0] grp_fu_340_p2;
wire   [25:0] grp_fu_342_p2;
wire   [25:0] grp_fu_336_p2;
wire   [25:0] grp_fu_341_p2;
wire   [25:0] grp_fu_338_p2;
wire   [25:0] grp_fu_339_p2;
wire   [25:0] grp_fu_337_p2;
wire   [24:0] grp_fu_1602_p1;
wire   [24:0] grp_fu_1612_p1;
wire   [22:0] shl_ln_fu_1720_p3;
wire   [19:0] shl_ln1118_1_fu_1731_p3;
wire  signed [23:0] sext_ln1118_62_fu_1738_p1;
wire  signed [23:0] sext_ln1118_61_fu_1727_p1;
wire   [23:0] add_ln1118_fu_1742_p2;
wire   [23:0] tmp_fu_1758_p1;
wire   [24:0] trunc_ln708_7_fu_1772_p1;
wire   [14:0] trunc_ln708_7_fu_1772_p4;
wire  signed [15:0] mult_128_V_fu_1782_p1;
wire   [15:0] add_ln703_fu_1786_p2;
wire   [24:0] trunc_ln708_3_fu_1808_p1;
wire   [23:0] shl_ln1118_5_fu_1822_p3;
wire  signed [24:0] sext_ln1118_69_fu_1829_p1;
wire   [21:0] shl_ln1118_6_fu_1839_p3;
wire   [24:0] sub_ln1118_3_fu_1833_p2;
wire  signed [24:0] sext_ln1118_70_fu_1846_p1;
wire   [24:0] sub_ln1118_4_fu_1850_p2;
wire   [14:0] trunc_ln708_4_fu_1856_p4;
wire  signed [15:0] mult_339_V_fu_1866_p1;
wire   [15:0] add_ln703_151_fu_1870_p2;
wire   [15:0] add_ln703_110_fu_1882_p2;
wire   [15:0] add_ln703_116_fu_1900_p2;
wire   [15:0] add_ln703_115_fu_1894_p2;
wire   [23:0] shl_ln1118_2_fu_1912_p3;
wire  signed [24:0] sext_ln1118_65_fu_1919_p1;
wire   [19:0] shl_ln1118_3_fu_1929_p3;
wire   [24:0] sub_ln1118_fu_1923_p2;
wire  signed [24:0] sext_ln1118_66_fu_1936_p1;
wire   [24:0] sub_ln1118_1_fu_1940_p2;
wire   [20:0] shl_ln1118_4_fu_1960_p3;
wire  signed [24:0] sext_ln1118_67_fu_1967_p1;
wire   [24:0] sub_ln1118_2_fu_1971_p2;
wire   [14:0] trunc_ln708_s_fu_1977_p4;
wire   [24:0] sub_ln1118_7_fu_1991_p2;
wire   [23:0] shl_ln1118_7_fu_2023_p3;
wire  signed [24:0] sext_ln1118_73_fu_2030_p1;
wire   [16:0] shl_ln1118_8_fu_2040_p3;
wire   [24:0] sub_ln1118_5_fu_2034_p2;
wire  signed [24:0] sext_ln1118_74_fu_2047_p1;
wire   [24:0] sub_ln1118_6_fu_2051_p2;
wire   [14:0] trunc_ln708_6_fu_2057_p4;
wire  signed [15:0] mult_390_V_fu_2019_p1;
wire   [15:0] add_ln703_89_fu_2071_p2;
wire  signed [15:0] mult_134_V_fu_1956_p1;
wire  signed [15:0] mult_411_V_fu_2067_p1;
wire   [15:0] add_ln703_108_fu_2083_p2;
wire  signed [15:0] mult_155_V_fu_1987_p1;
wire   [15:0] add_ln703_163_fu_2095_p2;
wire   [15:0] add_ln703_166_fu_2112_p2;
wire   [15:0] add_ln703_165_fu_2107_p2;
wire   [15:0] add_ln703_170_fu_2124_p2;
wire  signed [15:0] mult_253_V_fu_2006_p1;
wire   [15:0] add_ln703_99_fu_2141_p2;
wire   [15:0] add_ln703_100_fu_2147_p2;
wire   [15:0] add_ln703_98_fu_2136_p2;
wire   [15:0] add_ln703_106_fu_2163_p2;
wire   [15:0] add_ln703_105_fu_2158_p2;
wire   [15:0] add_ln703_121_fu_2175_p2;
wire   [15:0] add_ln703_124_fu_2190_p2;
wire   [15:0] add_ln703_127_fu_2201_p2;
wire   [15:0] add_ln703_129_fu_2212_p2;
wire   [15:0] add_ln703_133_fu_2224_p2;
wire   [15:0] add_ln703_136_fu_2240_p2;
wire   [15:0] add_ln703_135_fu_2235_p2;
wire   [15:0] add_ln703_138_fu_2252_p2;
wire  signed [15:0] mult_192_V_fu_2187_p1;
wire   [15:0] add_ln703_141_fu_2264_p2;
wire   [15:0] add_ln703_91_fu_2278_p2;
wire   [15:0] add_ln703_144_fu_2288_p2;
wire  signed [15:0] mult_73_V_fu_2275_p1;
wire   [15:0] add_ln703_146_fu_2300_p2;
wire   [15:0] add_ln703_155_fu_2311_p2;
wire   [15:0] add_ln703_159_fu_2322_p2;
wire   [15:0] add_ln703_84_fu_2347_p2;
wire  signed [15:0] mult_132_V_fu_2337_p1;
wire  signed [15:0] mult_160_V_fu_2340_p1;
wire  signed [14:0] sext_ln203_fu_2334_p1;
wire   [14:0] acc_85_V_fu_2503_p2;
wire  signed [15:0] mult_472_V_fu_2343_p1;
wire   [15:0] acc_2_V_fu_2353_p2;
wire   [15:0] acc_3_V_fu_2358_p2;
wire   [15:0] acc_4_V_fu_2364_p2;
wire   [15:0] acc_5_V_fu_2370_p2;
wire   [15:0] acc_10_V_fu_2375_p2;
wire   [15:0] acc_14_V_fu_2380_p2;
wire   [15:0] acc_15_V_fu_2385_p2;
wire   [15:0] acc_17_V_fu_2391_p2;
wire   [15:0] acc_18_V_fu_2396_p2;
wire   [15:0] acc_21_V_fu_2401_p2;
wire   [15:0] acc_23_V_fu_2406_p2;
wire   [15:0] acc_24_V_fu_2411_p2;
wire   [15:0] acc_30_V_fu_2416_p2;
wire   [15:0] acc_32_V_fu_2421_p2;
wire   [15:0] acc_34_V_fu_2427_p2;
wire   [15:0] acc_40_V_fu_2432_p2;
wire   [15:0] acc_42_V_fu_2437_p2;
wire   [15:0] acc_43_V_fu_2442_p2;
wire   [15:0] acc_47_V_fu_2448_p2;
wire   [15:0] acc_52_V_fu_2454_p2;
wire   [15:0] acc_56_V_fu_2459_p2;
wire   [15:0] acc_57_V_fu_2464_p2;
wire   [15:0] acc_66_V_fu_2469_p2;
wire   [15:0] acc_69_V_fu_2475_p2;
wire   [15:0] acc_79_V_fu_2481_p2;
wire   [15:0] acc_80_V_fu_2486_p2;
wire   [15:0] acc_82_V_fu_2492_p2;
wire   [15:0] acc_84_V_fu_2497_p2;
wire  signed [15:0] sext_ln703_fu_2509_p1;
wire   [15:0] acc_88_V_fu_2513_p2;
wire   [15:0] acc_91_V_fu_2519_p2;
wire   [15:0] acc_94_V_fu_2524_p2;
wire   [15:0] acc_98_V_fu_2530_p2;
wire   [15:0] acc_105_V_fu_2536_p2;
wire   [15:0] acc_107_V_fu_2542_p2;
reg   [10:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 11'd1;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state7))) begin
        acc_102_V_reg_3161 <= acc_102_V_fu_2101_p2;
        acc_103_V_reg_3166 <= acc_103_V_fu_2118_p2;
        acc_125_V_reg_3171 <= acc_125_V_fu_2130_p2;
        acc_27_V_reg_3156 <= acc_27_V_fu_2089_p2;
        acc_6_V_reg_3151 <= acc_6_V_fu_2077_p2;
        mult_363_V_reg_3124 <= {{grp_fu_341_p2[25:10]}};
        mult_389_V_reg_3146 <= {{grp_fu_337_p2[25:10]}};
        sext_ln1118_71_reg_3129 <= sext_ln1118_71_fu_2009_p1;
        sext_ln1118_72_reg_3134 <= sext_ln1118_72_fu_2013_p1;
        trunc_ln708_1_reg_3119 <= {{sub_ln1118_7_fu_1991_p2[24:10]}};
        trunc_ln708_8_reg_3114 <= {{sub_ln1118_1_fu_1940_p2[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8))) begin
        acc_19_V_reg_3196 <= acc_19_V_fu_2152_p2;
        acc_26_V_reg_3201 <= acc_26_V_fu_2169_p2;
        acc_45_V_reg_3206 <= acc_45_V_fu_2181_p2;
        mult_392_V_reg_3176 <= {{grp_fu_343_p2[25:10]}};
        mult_398_V_reg_3181 <= {{grp_fu_337_p2[25:10]}};
        mult_405_V_reg_3186 <= {{grp_fu_341_p2[25:10]}};
        mult_426_V_reg_3191 <= {{grp_fu_340_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state5))) begin
        acc_29_V_reg_3074 <= acc_29_V_fu_1888_p2;
        acc_35_V_reg_3079 <= acc_35_V_fu_1906_p2;
        mult_264_V_reg_3052 <= {{grp_fu_343_p2[25:10]}};
        mult_266_V_reg_3058 <= {{grp_fu_340_p2[25:10]}};
        mult_275_V_reg_3063 <= {{grp_fu_342_p2[25:10]}};
        mult_290_V_reg_3068 <= {{grp_fu_341_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state9))) begin
        acc_48_V_reg_3211 <= acc_48_V_fu_2196_p2;
        acc_53_V_reg_3216 <= acc_53_V_fu_2207_p2;
        acc_54_V_reg_3221 <= acc_54_V_fu_2218_p2;
        acc_62_V_reg_3226 <= acc_62_V_fu_2230_p2;
        acc_63_V_reg_3231 <= acc_63_V_fu_2246_p2;
        acc_64_V_reg_3236 <= acc_64_V_fu_2258_p2;
        acc_67_V_reg_3241 <= acc_67_V_fu_2270_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state10))) begin
        acc_73_V_reg_3251 <= acc_73_V_fu_2294_p2;
        acc_75_V_reg_3256 <= acc_75_V_fu_2306_p2;
        acc_87_V_reg_3261 <= acc_87_V_fu_2317_p2;
        acc_8_V_reg_3246 <= acc_8_V_fu_2283_p2;
        acc_93_V_reg_3266 <= acc_93_V_fu_2328_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4))) begin
        acc_83_V_reg_3047 <= acc_83_V_fu_1876_p2;
        mult_185_V_reg_3000 <= {{grp_fu_343_p2[25:10]}};
        mult_191_V_reg_3005 <= {{grp_fu_340_p2[25:10]}};
        mult_219_V_reg_3015 <= {{grp_fu_341_p2[25:10]}};
        mult_231_V_reg_3020 <= {{grp_fu_338_p2[25:10]}};
        mult_258_V_reg_3042 <= {{grp_fu_337_p2[25:10]}};
        sext_ln1118_68_reg_3030 <= sext_ln1118_68_fu_1818_p1;
        trunc_ln708_2_reg_3010 <= {{grp_fu_1612_p1[24:10]}};
        trunc_ln708_3_reg_3025 <= {{trunc_ln708_3_fu_1808_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln703_83_reg_2961 <= add_ln703_83_fu_1792_p2;
        mult_79_V_reg_2938 <= {{grp_fu_340_p2[25:10]}};
        mult_82_V_reg_2943 <= {{grp_fu_342_p2[25:10]}};
        sext_ln1118_64_reg_2953 <= sext_ln1118_64_fu_1768_p1;
        tmp_reg_2948 <= {{tmp_fu_1758_p1[23:10]}};
        trunc_ln_reg_2933 <= {{add_ln1118_fu_1742_p2[23:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3))) begin
        mult_146_V_reg_2975 <= {{grp_fu_340_p2[25:10]}};
        mult_147_V_reg_2980 <= {{grp_fu_342_p2[25:10]}};
        mult_151_V_reg_2985 <= {{grp_fu_336_p2[25:10]}};
        mult_152_V_reg_2990 <= {{grp_fu_341_p2[25:10]}};
        mult_154_V_reg_2995 <= {{grp_fu_338_p2[25:10]}};
        sext_ln1118_63_reg_2966 <= sext_ln1118_63_fu_1798_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        mult_17_V_reg_2894 <= {{grp_fu_340_p2[25:10]}};
        mult_30_V_reg_2899 <= {{grp_fu_341_p2[25:10]}};
        mult_40_V_reg_2904 <= {{grp_fu_339_p2[25:10]}};
        sext_ln1118_60_reg_2884 <= sext_ln1118_60_fu_1674_p1;
        tmp_1_reg_2909 <= {{data_V_read[31:16]}};
        tmp_2_reg_2918 <= {{data_V_read[47:32]}};
        tmp_3_reg_2925 <= {{data_V_read[63:48]}};
        trunc_ln203_reg_2877 <= trunc_ln203_fu_1670_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state6))) begin
        mult_304_V_reg_3084 <= {{grp_fu_343_p2[25:10]}};
        mult_309_V_reg_3089 <= {{grp_fu_340_p2[25:10]}};
        mult_312_V_reg_3094 <= {{grp_fu_342_p2[25:10]}};
        mult_318_V_reg_3099 <= {{grp_fu_336_p2[25:10]}};
        mult_323_V_reg_3104 <= {{grp_fu_339_p2[25:10]}};
        mult_331_V_reg_3109 <= {{grp_fu_337_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        reg_1622 <= {{grp_fu_343_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        reg_1626 <= {{grp_fu_342_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state10)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        reg_1630 <= {{grp_fu_336_p2[25:10]}};
        reg_1638 <= {{grp_fu_337_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state6)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1)))) begin
        reg_1634 <= {{grp_fu_338_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state10)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        reg_1642 <= {{grp_fu_341_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state7)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2)))) begin
        reg_1646 <= {{grp_fu_338_p2[25:10]}};
        reg_1650 <= {{grp_fu_339_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state10)))) begin
        reg_1654 <= {{grp_fu_1602_p1[24:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state5)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3)))) begin
        reg_1658 <= {{grp_fu_339_p2[25:10]}};
        reg_1662 <= {{grp_fu_337_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state9)) | ((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state6)))) begin
        reg_1666 <= {{grp_fu_341_p2[25:10]}};
    end
end

always @ (*) begin
    if ((((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state11)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_336_p0 = 26'd67108502;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_336_p0 = 26'd67108535;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_336_p0 = 26'd447;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_fu_336_p0 = 26'd338;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_336_p0 = 26'd366;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_336_p0 = 26'd67108574;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_336_p0 = 24'd16777121;
    end else if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_fu_336_p0 = 26'd328;
    end else begin
        grp_fu_336_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_336_p1 = sext_ln1118_72_reg_3134;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_336_p1 = sext_ln1118_68_reg_3030;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_336_p1 = sext_ln1118_63_reg_2966;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_336_p1 = sext_ln1118_63_fu_1798_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_336_p1 = sext_ln1118_fu_1716_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_336_p1 = sext_ln1118_60_fu_1674_p1;
    end else begin
        grp_fu_336_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_337_p0 = 26'd422;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_337_p0 = 26'd364;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_337_p0 = 26'd360;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_337_p0 = 26'd392;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_337_p0 = 26'd402;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_337_p0 = 26'd67108464;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_337_p0 = 26'd411;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_337_p0 = 26'd271;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_337_p0 = 25'd228;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_337_p0 = 26'd67108519;
    end else begin
        grp_fu_337_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_337_p1 = sext_ln1118_72_reg_3134;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_337_p1 = sext_ln1118_72_fu_2013_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_337_p1 = sext_ln1118_68_reg_3030;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_337_p1 = sext_ln1118_68_fu_1818_p1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_337_p1 = sext_ln1118_63_fu_1798_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_337_p1 = sext_ln1118_64_fu_1768_p1;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_337_p1 = sext_ln1118_60_fu_1674_p1;
    end else begin
        grp_fu_337_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_338_p0 = 26'd451;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_338_p0 = 26'd404;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_338_p0 = 26'd345;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_338_p0 = 26'd385;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_338_p0 = 26'd67108492;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_338_p0 = 26'd316;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state3))) begin
        grp_fu_338_p0 = 26'd67108460;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_338_p0 = 26'd67108527;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_338_p0 = 26'd67108481;
    end else begin
        grp_fu_338_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_338_p1 = sext_ln1118_72_reg_3134;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_338_p1 = sext_ln1118_72_fu_2013_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_338_p1 = sext_ln1118_68_reg_3030;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_338_p1 = sext_ln1118_63_reg_2966;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_338_p1 = sext_ln1118_63_fu_1798_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_338_p1 = sext_ln1118_60_reg_2884;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_338_p1 = sext_ln1118_60_fu_1674_p1;
    end else begin
        grp_fu_338_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_339_p0 = 26'd67108529;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_339_p0 = 26'd67108515;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_339_p0 = 26'd321;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_339_p0 = 26'd67108456;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state5))) begin
        grp_fu_339_p0 = 26'd358;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_339_p0 = 25'd243;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_339_p0 = 26'd67108597;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state2))) begin
        grp_fu_339_p0 = 26'd67108501;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_339_p0 = 26'd383;
    end else begin
        grp_fu_339_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_339_p1 = sext_ln1118_72_reg_3134;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_339_p1 = sext_ln1118_72_fu_2013_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_339_p1 = sext_ln1118_68_reg_3030;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_339_p1 = sext_ln1118_64_reg_2953;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_339_p1 = sext_ln1118_63_fu_1798_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_339_p1 = sext_ln1118_60_reg_2884;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_339_p1 = sext_ln1118_60_fu_1674_p1;
    end else begin
        grp_fu_339_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_340_p0 = 26'd319;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_340_p0 = 26'd67108490;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_340_p0 = 26'd429;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_340_p0 = 26'd67108451;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_340_p0 = 26'd67108518;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_340_p0 = 26'd446;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_340_p0 = 26'd67108462;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_340_p0 = 26'd67108508;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_340_p0 = 26'd67108526;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_340_p0 = 26'd365;
    end else begin
        grp_fu_340_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_340_p1 = sext_ln1118_72_reg_3134;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_340_p1 = sext_ln1118_68_reg_3030;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_340_p1 = sext_ln1118_63_reg_2966;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_340_p1 = sext_ln1118_63_fu_1798_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_340_p1 = sext_ln1118_60_reg_2884;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_340_p1 = sext_ln1118_60_fu_1674_p1;
    end else begin
        grp_fu_340_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_341_p0 = 26'd366;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_341_p0 = 26'd488;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_341_p0 = 26'd67108444;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_341_p0 = 26'd348;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_341_p0 = 26'd375;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_341_p0 = 26'd341;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_341_p0 = 26'd67108482;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_341_p0 = 26'd67108580;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_341_p0 = 26'd303;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_341_p0 = 26'd67108487;
    end else begin
        grp_fu_341_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_341_p1 = sext_ln1118_72_reg_3134;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_341_p1 = sext_ln1118_68_reg_3030;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_341_p1 = sext_ln1118_63_reg_2966;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_341_p1 = sext_ln1118_63_fu_1798_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_341_p1 = sext_ln1118_60_reg_2884;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_341_p1 = sext_ln1118_60_fu_1674_p1;
    end else begin
        grp_fu_341_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_342_p0 = 26'd438;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_342_p0 = 26'd67108494;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_342_p0 = 26'd67108545;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_342_p0 = 25'd33554201;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_342_p0 = 26'd67108598;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_342_p0 = 26'd67108438;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_342_p0 = 25'd33554241;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_342_p0 = 26'd306;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_342_p0 = 26'd67108553;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_342_p0 = 26'd67108547;
    end else begin
        grp_fu_342_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_342_p1 = sext_ln1118_72_reg_3134;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_342_p1 = sext_ln1118_71_fu_2009_p1;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_342_p1 = sext_ln1118_68_reg_3030;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_342_p1 = sext_ln1118_64_reg_2953;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_342_p1 = sext_ln1118_63_fu_1798_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_342_p1 = sext_ln1118_60_reg_2884;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_342_p1 = sext_ln1118_60_fu_1674_p1;
    end else begin
        grp_fu_342_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_343_p0 = 25'd33554182;
    end else if ((1'b1 == ap_CS_fsm_state9)) begin
        grp_fu_343_p0 = 26'd409;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        grp_fu_343_p0 = 26'd333;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_fu_343_p0 = 26'd67108456;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_343_p0 = 26'd332;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        grp_fu_343_p0 = 26'd363;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_343_p0 = 26'd370;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_343_p0 = 25'd33554195;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_343_p0 = 26'd67108532;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_343_p0 = 26'd67108510;
    end else begin
        grp_fu_343_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        grp_fu_343_p1 = sext_ln1118_71_reg_3129;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8))) begin
        grp_fu_343_p1 = sext_ln1118_72_reg_3134;
    end else if (((1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_343_p1 = sext_ln1118_68_reg_3030;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_343_p1 = sext_ln1118_63_reg_2966;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        grp_fu_343_p1 = sext_ln1118_64_reg_2953;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_343_p1 = sext_ln1118_60_reg_2884;
    end else if ((1'b1 == ap_CS_fsm_state1)) begin
        grp_fu_343_p1 = sext_ln1118_60_fu_1674_p1;
    end else begin
        grp_fu_343_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state10 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if (((1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_102_V_fu_2101_p2 = (add_ln703_163_fu_2095_p2 + reg_1646);

assign acc_103_V_fu_2118_p2 = (add_ln703_166_fu_2112_p2 + add_ln703_165_fu_2107_p2);

assign acc_105_V_fu_2536_p2 = ($signed(16'd65494) + $signed(grp_fu_1582_p4));

assign acc_107_V_fu_2542_p2 = (16'd133 + mult_363_V_reg_3124);

assign acc_10_V_fu_2375_p2 = (16'd5 + mult_266_V_reg_3058);

assign acc_125_V_fu_2130_p2 = ($signed(add_ln703_170_fu_2124_p2) + $signed(mult_253_V_fu_2006_p1));

assign acc_14_V_fu_2380_p2 = ($signed(16'd65461) + $signed(mult_398_V_reg_3181));

assign acc_15_V_fu_2385_p2 = (16'd303 + reg_1626);

assign acc_17_V_fu_2391_p2 = (16'd281 + mult_17_V_reg_2894);

assign acc_18_V_fu_2396_p2 = (16'd250 + mult_146_V_reg_2975);

assign acc_19_V_fu_2152_p2 = (add_ln703_100_fu_2147_p2 + add_ln703_98_fu_2136_p2);

assign acc_21_V_fu_2401_p2 = (16'd30 + mult_405_V_reg_3186);

assign acc_23_V_fu_2406_p2 = (16'd257 + mult_151_V_reg_2985);

assign acc_24_V_fu_2411_p2 = (16'd222 + mult_152_V_reg_2990);

assign acc_26_V_fu_2169_p2 = (add_ln703_106_fu_2163_p2 + add_ln703_105_fu_2158_p2);

assign acc_27_V_fu_2089_p2 = ($signed(add_ln703_108_fu_2083_p2) + $signed(mult_155_V_fu_1987_p1));

assign acc_29_V_fu_1888_p2 = (add_ln703_110_fu_1882_p2 + reg_1658);

assign acc_2_V_fu_2353_p2 = (add_ln703_84_fu_2347_p2 + mult_258_V_reg_3042);

assign acc_30_V_fu_2416_p2 = ($signed(16'd65476) + $signed(mult_30_V_reg_2899));

assign acc_32_V_fu_2421_p2 = ($signed(16'd234) + $signed(mult_160_V_fu_2340_p1));

assign acc_34_V_fu_2427_p2 = ($signed(16'd65527) + $signed(mult_290_V_reg_3068));

assign acc_35_V_fu_1906_p2 = (add_ln703_116_fu_1900_p2 + add_ln703_115_fu_1894_p2);

assign acc_3_V_fu_2358_p2 = (16'd67 + reg_1650);

assign acc_40_V_fu_2432_p2 = (16'd316 + mult_40_V_reg_2904);

assign acc_42_V_fu_2437_p2 = ($signed(16'd65523) + $signed(mult_426_V_reg_3191));

assign acc_43_V_fu_2442_p2 = ($signed(16'd65495) + $signed(reg_1646));

assign acc_45_V_fu_2181_p2 = (add_ln703_121_fu_2175_p2 + reg_1658);

assign acc_47_V_fu_2448_p2 = (16'd122 + reg_1662);

assign acc_48_V_fu_2196_p2 = (add_ln703_124_fu_2190_p2 + mult_304_V_reg_3084);

assign acc_4_V_fu_2364_p2 = ($signed(16'd241) + $signed(mult_132_V_fu_2337_p1));

assign acc_52_V_fu_2454_p2 = (16'd149 + mult_290_V_reg_3068);

assign acc_53_V_fu_2207_p2 = (add_ln703_127_fu_2201_p2 + mult_309_V_reg_3089);

assign acc_54_V_fu_2218_p2 = (add_ln703_129_fu_2212_p2 + reg_1638);

assign acc_56_V_fu_2459_p2 = (16'd288 + mult_312_V_reg_3094);

assign acc_57_V_fu_2464_p2 = (16'd260 + mult_185_V_reg_3000);

assign acc_5_V_fu_2370_p2 = ($signed(16'd65487) + $signed(mult_389_V_reg_3146));

assign acc_62_V_fu_2230_p2 = (add_ln703_133_fu_2224_p2 + mult_318_V_reg_3099);

assign acc_63_V_fu_2246_p2 = (add_ln703_136_fu_2240_p2 + add_ln703_135_fu_2235_p2);

assign acc_64_V_fu_2258_p2 = ($signed(add_ln703_138_fu_2252_p2) + $signed(mult_192_V_fu_2187_p1));

assign acc_66_V_fu_2469_p2 = ($signed(16'd65516) + $signed(reg_1666));

assign acc_67_V_fu_2270_p2 = (add_ln703_141_fu_2264_p2 + mult_323_V_reg_3104);

assign acc_69_V_fu_2475_p2 = (16'd150 + reg_1622);

assign acc_6_V_fu_2077_p2 = ($signed(add_ln703_89_fu_2071_p2) + $signed(mult_134_V_fu_1956_p1));

assign acc_73_V_fu_2294_p2 = ($signed(add_ln703_144_fu_2288_p2) + $signed(mult_73_V_fu_2275_p1));

assign acc_75_V_fu_2306_p2 = (add_ln703_146_fu_2300_p2 + mult_331_V_reg_3109);

assign acc_79_V_fu_2481_p2 = (16'd10 + mult_79_V_reg_2938);

assign acc_80_V_fu_2486_p2 = ($signed(16'd65518) + $signed(reg_1630));

assign acc_82_V_fu_2492_p2 = (16'd95 + mult_82_V_reg_2943);

assign acc_83_V_fu_1876_p2 = (add_ln703_151_fu_1870_p2 + grp_fu_1552_p4);

assign acc_84_V_fu_2497_p2 = ($signed(16'd65489) + $signed(reg_1642));

assign acc_85_V_fu_2503_p2 = ($signed(15'd211) + $signed(sext_ln203_fu_2334_p1));

assign acc_87_V_fu_2317_p2 = (add_ln703_155_fu_2311_p2 + mult_264_V_reg_3052);

assign acc_88_V_fu_2513_p2 = ($signed(16'd231) + $signed(mult_472_V_fu_2343_p1));

assign acc_8_V_fu_2283_p2 = (add_ln703_91_fu_2278_p2 + mult_264_V_reg_3052);

assign acc_91_V_fu_2519_p2 = (16'd288 + mult_219_V_reg_3015);

assign acc_93_V_fu_2328_p2 = (add_ln703_159_fu_2322_p2 + reg_1642);

assign acc_94_V_fu_2524_p2 = (16'd303 + reg_1638);

assign acc_98_V_fu_2530_p2 = ($signed(16'd65462) + $signed(reg_1634));

assign add_ln1118_fu_1742_p2 = ($signed(sext_ln1118_62_fu_1738_p1) + $signed(sext_ln1118_61_fu_1727_p1));

assign add_ln703_100_fu_2147_p2 = (add_ln703_99_fu_2141_p2 + mult_275_V_reg_3063);

assign add_ln703_105_fu_2158_p2 = (reg_1630 + mult_154_V_reg_2995);

assign add_ln703_106_fu_2163_p2 = (16'd225 + grp_fu_1572_p4);

assign add_ln703_108_fu_2083_p2 = ($signed(16'd234) + $signed(mult_411_V_fu_2067_p1));

assign add_ln703_110_fu_1882_p2 = (16'd246 + grp_fu_1552_p4);

assign add_ln703_115_fu_1894_p2 = (reg_1634 + reg_1662);

assign add_ln703_116_fu_1900_p2 = ($signed(16'd65535) + $signed(grp_fu_1572_p4));

assign add_ln703_121_fu_2175_p2 = ($signed(16'd65412) + $signed(grp_fu_1582_p4));

assign add_ln703_124_fu_2190_p2 = ($signed(16'd65449) + $signed(grp_fu_1552_p4));

assign add_ln703_127_fu_2201_p2 = (16'd126 + grp_fu_1572_p4);

assign add_ln703_129_fu_2212_p2 = (16'd13 + grp_fu_1532_p4);

assign add_ln703_133_fu_2224_p2 = (16'd235 + grp_fu_1592_p4);

assign add_ln703_135_fu_2235_p2 = (mult_191_V_reg_3005 + reg_1666);

assign add_ln703_136_fu_2240_p2 = (16'd286 + grp_fu_1522_p4);

assign add_ln703_138_fu_2252_p2 = (16'd286 + grp_fu_1582_p4);

assign add_ln703_141_fu_2264_p2 = (16'd130 + grp_fu_1542_p4);

assign add_ln703_144_fu_2288_p2 = (16'd349 + grp_fu_1582_p4);

assign add_ln703_146_fu_2300_p2 = ($signed(16'd65468) + $signed(grp_fu_1542_p4));

assign add_ln703_151_fu_1870_p2 = ($signed(16'd115) + $signed(mult_339_V_fu_1866_p1));

assign add_ln703_155_fu_2311_p2 = ($signed(16'd65443) + $signed(grp_fu_1572_p4));

assign add_ln703_159_fu_2322_p2 = (16'd75 + grp_fu_1532_p4);

assign add_ln703_163_fu_2095_p2 = (16'd203 + grp_fu_1532_p4);

assign add_ln703_165_fu_2107_p2 = (reg_1650 + mult_231_V_reg_3020);

assign add_ln703_166_fu_2112_p2 = (16'd99 + grp_fu_1552_p4);

assign add_ln703_170_fu_2124_p2 = (16'd135 + grp_fu_1522_p4);

assign add_ln703_83_fu_1792_p2 = (add_ln703_fu_1786_p2 + reg_1622);

assign add_ln703_84_fu_2347_p2 = ($signed(16'd65405) + $signed(reg_1646));

assign add_ln703_89_fu_2071_p2 = ($signed(16'd237) + $signed(mult_390_V_fu_2019_p1));

assign add_ln703_91_fu_2278_p2 = (16'd250 + mult_392_V_reg_3176);

assign add_ln703_98_fu_2136_p2 = (reg_1626 + mult_147_V_reg_2980);

assign add_ln703_99_fu_2141_p2 = (16'd185 + grp_fu_1552_p4);

assign add_ln703_fu_1786_p2 = ($signed(16'd27) + $signed(mult_128_V_fu_1782_p1));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_return_0 = add_ln703_83_reg_2961;

assign ap_return_1 = acc_2_V_fu_2353_p2;

assign ap_return_10 = acc_17_V_fu_2391_p2;

assign ap_return_11 = acc_18_V_fu_2396_p2;

assign ap_return_12 = acc_19_V_reg_3196;

assign ap_return_13 = acc_21_V_fu_2401_p2;

assign ap_return_14 = acc_23_V_fu_2406_p2;

assign ap_return_15 = acc_24_V_fu_2411_p2;

assign ap_return_16 = acc_26_V_reg_3201;

assign ap_return_17 = acc_27_V_reg_3156;

assign ap_return_18 = acc_29_V_reg_3074;

assign ap_return_19 = acc_30_V_fu_2416_p2;

assign ap_return_2 = acc_3_V_fu_2358_p2;

assign ap_return_20 = acc_32_V_fu_2421_p2;

assign ap_return_21 = acc_34_V_fu_2427_p2;

assign ap_return_22 = acc_35_V_reg_3079;

assign ap_return_23 = acc_40_V_fu_2432_p2;

assign ap_return_24 = acc_42_V_fu_2437_p2;

assign ap_return_25 = acc_43_V_fu_2442_p2;

assign ap_return_26 = acc_45_V_reg_3206;

assign ap_return_27 = acc_47_V_fu_2448_p2;

assign ap_return_28 = acc_48_V_reg_3211;

assign ap_return_29 = acc_52_V_fu_2454_p2;

assign ap_return_3 = acc_4_V_fu_2364_p2;

assign ap_return_30 = acc_53_V_reg_3216;

assign ap_return_31 = acc_54_V_reg_3221;

assign ap_return_32 = acc_56_V_fu_2459_p2;

assign ap_return_33 = acc_57_V_fu_2464_p2;

assign ap_return_34 = acc_62_V_reg_3226;

assign ap_return_35 = acc_63_V_reg_3231;

assign ap_return_36 = acc_64_V_reg_3236;

assign ap_return_37 = acc_66_V_fu_2469_p2;

assign ap_return_38 = acc_67_V_reg_3241;

assign ap_return_39 = acc_69_V_fu_2475_p2;

assign ap_return_4 = acc_5_V_fu_2370_p2;

assign ap_return_40 = acc_73_V_reg_3251;

assign ap_return_41 = acc_75_V_reg_3256;

assign ap_return_42 = acc_79_V_fu_2481_p2;

assign ap_return_43 = acc_80_V_fu_2486_p2;

assign ap_return_44 = acc_82_V_fu_2492_p2;

assign ap_return_45 = acc_83_V_reg_3047;

assign ap_return_46 = acc_84_V_fu_2497_p2;

assign ap_return_47 = sext_ln703_fu_2509_p1;

assign ap_return_48 = acc_87_V_reg_3261;

assign ap_return_49 = acc_88_V_fu_2513_p2;

assign ap_return_5 = acc_6_V_reg_3151;

assign ap_return_50 = acc_91_V_fu_2519_p2;

assign ap_return_51 = acc_93_V_reg_3266;

assign ap_return_52 = acc_94_V_fu_2524_p2;

assign ap_return_53 = acc_98_V_fu_2530_p2;

assign ap_return_54 = acc_102_V_reg_3161;

assign ap_return_55 = acc_103_V_reg_3166;

assign ap_return_56 = acc_105_V_fu_2536_p2;

assign ap_return_57 = acc_107_V_fu_2542_p2;

assign ap_return_58 = acc_125_V_reg_3171;

assign ap_return_6 = acc_8_V_reg_3246;

assign ap_return_7 = acc_10_V_fu_2375_p2;

assign ap_return_8 = acc_14_V_fu_2380_p2;

assign ap_return_9 = acc_15_V_fu_2385_p2;

assign grp_fu_1522_p4 = {{grp_fu_343_p2[25:10]}};

assign grp_fu_1532_p4 = {{grp_fu_340_p2[25:10]}};

assign grp_fu_1542_p4 = {{grp_fu_342_p2[25:10]}};

assign grp_fu_1552_p4 = {{grp_fu_336_p2[25:10]}};

assign grp_fu_1572_p4 = {{grp_fu_338_p2[25:10]}};

assign grp_fu_1582_p4 = {{grp_fu_339_p2[25:10]}};

assign grp_fu_1592_p4 = {{grp_fu_337_p2[25:10]}};

assign grp_fu_1602_p1 = grp_fu_343_p2;

assign grp_fu_1612_p1 = grp_fu_342_p2;

assign grp_fu_1612_p4 = {{grp_fu_1612_p1[24:10]}};

assign grp_fu_336_p2 = ($signed(grp_fu_336_p0) * $signed(grp_fu_336_p1));

assign grp_fu_337_p2 = ($signed(grp_fu_337_p0) * $signed(grp_fu_337_p1));

assign grp_fu_338_p2 = ($signed(grp_fu_338_p0) * $signed(grp_fu_338_p1));

assign grp_fu_339_p2 = ($signed(grp_fu_339_p0) * $signed(grp_fu_339_p1));

assign grp_fu_340_p2 = ($signed(grp_fu_340_p0) * $signed(grp_fu_340_p1));

assign grp_fu_341_p2 = ($signed(grp_fu_341_p0) * $signed(grp_fu_341_p1));

assign grp_fu_342_p2 = ($signed(grp_fu_342_p0) * $signed(grp_fu_342_p1));

assign grp_fu_343_p2 = ($signed(grp_fu_343_p0) * $signed(grp_fu_343_p1));

assign mult_128_V_fu_1782_p1 = $signed(trunc_ln708_7_fu_1772_p4);

assign mult_132_V_fu_2337_p1 = $signed(trunc_ln708_8_reg_3114);

assign mult_134_V_fu_1956_p1 = $signed(reg_1654);

assign mult_155_V_fu_1987_p1 = $signed(trunc_ln708_s_fu_1977_p4);

assign mult_160_V_fu_2340_p1 = $signed(trunc_ln708_1_reg_3119);

assign mult_192_V_fu_2187_p1 = $signed(trunc_ln708_2_reg_3010);

assign mult_253_V_fu_2006_p1 = $signed(trunc_ln708_3_reg_3025);

assign mult_339_V_fu_1866_p1 = $signed(trunc_ln708_4_fu_1856_p4);

assign mult_390_V_fu_2019_p1 = $signed(grp_fu_1612_p4);

assign mult_411_V_fu_2067_p1 = $signed(trunc_ln708_6_fu_2057_p4);

assign mult_472_V_fu_2343_p1 = $signed(reg_1654);

assign mult_73_V_fu_2275_p1 = $signed(trunc_ln_reg_2933);

assign sext_ln1118_60_fu_1674_p1 = trunc_ln203_fu_1670_p1;

assign sext_ln1118_61_fu_1727_p1 = $signed(shl_ln_fu_1720_p3);

assign sext_ln1118_62_fu_1738_p1 = $signed(shl_ln1118_1_fu_1731_p3);

assign sext_ln1118_63_fu_1798_p1 = tmp_1_reg_2909;

assign sext_ln1118_64_fu_1768_p1 = tmp_1_reg_2909;

assign sext_ln1118_65_fu_1919_p1 = $signed(shl_ln1118_2_fu_1912_p3);

assign sext_ln1118_66_fu_1936_p1 = $signed(shl_ln1118_3_fu_1929_p3);

assign sext_ln1118_67_fu_1967_p1 = $signed(shl_ln1118_4_fu_1960_p3);

assign sext_ln1118_68_fu_1818_p1 = tmp_2_reg_2918;

assign sext_ln1118_69_fu_1829_p1 = $signed(shl_ln1118_5_fu_1822_p3);

assign sext_ln1118_70_fu_1846_p1 = $signed(shl_ln1118_6_fu_1839_p3);

assign sext_ln1118_71_fu_2009_p1 = tmp_3_reg_2925;

assign sext_ln1118_72_fu_2013_p1 = tmp_3_reg_2925;

assign sext_ln1118_73_fu_2030_p1 = $signed(shl_ln1118_7_fu_2023_p3);

assign sext_ln1118_74_fu_2047_p1 = $signed(shl_ln1118_8_fu_2040_p3);

assign sext_ln1118_fu_1716_p1 = trunc_ln203_reg_2877;

assign sext_ln203_fu_2334_p1 = $signed(tmp_reg_2948);

assign sext_ln703_fu_2509_p1 = $signed(acc_85_V_fu_2503_p2);

assign shl_ln1118_1_fu_1731_p3 = {{trunc_ln203_reg_2877}, {4'd0}};

assign shl_ln1118_2_fu_1912_p3 = {{tmp_1_reg_2909}, {8'd0}};

assign shl_ln1118_3_fu_1929_p3 = {{tmp_1_reg_2909}, {4'd0}};

assign shl_ln1118_4_fu_1960_p3 = {{tmp_1_reg_2909}, {5'd0}};

assign shl_ln1118_5_fu_1822_p3 = {{tmp_2_reg_2918}, {8'd0}};

assign shl_ln1118_6_fu_1839_p3 = {{tmp_2_reg_2918}, {6'd0}};

assign shl_ln1118_7_fu_2023_p3 = {{tmp_3_reg_2925}, {8'd0}};

assign shl_ln1118_8_fu_2040_p3 = {{tmp_3_reg_2925}, {1'd0}};

assign shl_ln_fu_1720_p3 = {{trunc_ln203_reg_2877}, {7'd0}};

assign sub_ln1118_1_fu_1940_p2 = ($signed(sub_ln1118_fu_1923_p2) - $signed(sext_ln1118_66_fu_1936_p1));

assign sub_ln1118_2_fu_1971_p2 = ($signed(sext_ln1118_67_fu_1967_p1) - $signed(sext_ln1118_65_fu_1919_p1));

assign sub_ln1118_3_fu_1833_p2 = ($signed(25'd0) - $signed(sext_ln1118_69_fu_1829_p1));

assign sub_ln1118_4_fu_1850_p2 = ($signed(sub_ln1118_3_fu_1833_p2) - $signed(sext_ln1118_70_fu_1846_p1));

assign sub_ln1118_5_fu_2034_p2 = ($signed(25'd0) - $signed(sext_ln1118_73_fu_2030_p1));

assign sub_ln1118_6_fu_2051_p2 = ($signed(sub_ln1118_5_fu_2034_p2) - $signed(sext_ln1118_74_fu_2047_p1));

assign sub_ln1118_7_fu_1991_p2 = ($signed(sext_ln1118_64_reg_2953) - $signed(sext_ln1118_65_fu_1919_p1));

assign sub_ln1118_fu_1923_p2 = ($signed(25'd0) - $signed(sext_ln1118_65_fu_1919_p1));

assign tmp_fu_1758_p1 = grp_fu_336_p2;

assign trunc_ln203_fu_1670_p1 = data_V_read[15:0];

assign trunc_ln708_3_fu_1808_p1 = grp_fu_339_p2;

assign trunc_ln708_4_fu_1856_p4 = {{sub_ln1118_4_fu_1850_p2[24:10]}};

assign trunc_ln708_6_fu_2057_p4 = {{sub_ln1118_6_fu_2051_p2[24:10]}};

assign trunc_ln708_7_fu_1772_p1 = grp_fu_337_p2;

assign trunc_ln708_7_fu_1772_p4 = {{trunc_ln708_7_fu_1772_p1[24:10]}};

assign trunc_ln708_s_fu_1977_p4 = {{sub_ln1118_2_fu_1971_p2[24:10]}};

endmodule //dense_latency_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_0_s
