Backend: Vivado
ClockPeriod: 25
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 16
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'Folder_2_HLS4ML_Vivado_HLS/models/hls4ml_prj/keras_model.h5'
OutputDir: Folder_2_HLS4ML_Vivado_HLS/models/hls4ml_prj
OutputPredictions: null
Part: xcu50-fsvh2104-2-e
ProjectName: myproject
Stamp: 49c0bae9
Version: 1.0.0
