Backend: Vivado
ClockPeriod: 10
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<16,6>
    ReuseFactor: 64
    Strategy: Latency
    TraceOutput: false
IOType: io_stream
InputData: null
KerasModel: !keras_model 'Folder_2_HLS4ML_Vivado_HLS/models/hls4ml_prj/keras_model.h5'
OutputDir: Folder_2_HLS4ML_Vivado_HLS/models/hls4ml_prj
OutputPredictions: null
Part: xc7z020clg400-1
ProjectName: myproject
Stamp: D924d2C1
Version: 1.0.0
