-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config10_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_V_data_0_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_0_V_empty_n : IN STD_LOGIC;
    data_V_data_0_V_read : OUT STD_LOGIC;
    data_V_data_1_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_1_V_empty_n : IN STD_LOGIC;
    data_V_data_1_V_read : OUT STD_LOGIC;
    data_V_data_2_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_2_V_empty_n : IN STD_LOGIC;
    data_V_data_2_V_read : OUT STD_LOGIC;
    data_V_data_3_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_3_V_empty_n : IN STD_LOGIC;
    data_V_data_3_V_read : OUT STD_LOGIC;
    data_V_data_4_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_4_V_empty_n : IN STD_LOGIC;
    data_V_data_4_V_read : OUT STD_LOGIC;
    data_V_data_5_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_5_V_empty_n : IN STD_LOGIC;
    data_V_data_5_V_read : OUT STD_LOGIC;
    data_V_data_6_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_6_V_empty_n : IN STD_LOGIC;
    data_V_data_6_V_read : OUT STD_LOGIC;
    data_V_data_7_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_7_V_empty_n : IN STD_LOGIC;
    data_V_data_7_V_read : OUT STD_LOGIC;
    data_V_data_8_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_8_V_empty_n : IN STD_LOGIC;
    data_V_data_8_V_read : OUT STD_LOGIC;
    data_V_data_9_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    data_V_data_9_V_empty_n : IN STD_LOGIC;
    data_V_data_9_V_read : OUT STD_LOGIC;
    res_V_data_0_V_TREADY : IN STD_LOGIC;
    res_V_data_0_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_0_V_TVALID : OUT STD_LOGIC;
    res_V_data_1_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_1_V_TVALID : OUT STD_LOGIC;
    res_V_data_1_V_TREADY : IN STD_LOGIC;
    res_V_data_2_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_2_V_TVALID : OUT STD_LOGIC;
    res_V_data_2_V_TREADY : IN STD_LOGIC;
    res_V_data_3_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_3_V_TVALID : OUT STD_LOGIC;
    res_V_data_3_V_TREADY : IN STD_LOGIC;
    res_V_data_4_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_4_V_TVALID : OUT STD_LOGIC;
    res_V_data_4_V_TREADY : IN STD_LOGIC;
    res_V_data_5_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_5_V_TVALID : OUT STD_LOGIC;
    res_V_data_5_V_TREADY : IN STD_LOGIC;
    res_V_data_6_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_6_V_TVALID : OUT STD_LOGIC;
    res_V_data_6_V_TREADY : IN STD_LOGIC;
    res_V_data_7_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_7_V_TVALID : OUT STD_LOGIC;
    res_V_data_7_V_TREADY : IN STD_LOGIC;
    res_V_data_8_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_8_V_TVALID : OUT STD_LOGIC;
    res_V_data_8_V_TREADY : IN STD_LOGIC;
    res_V_data_9_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_V_data_9_V_TVALID : OUT STD_LOGIC;
    res_V_data_9_V_TREADY : IN STD_LOGIC );
end;


architecture behav of relu_array_ap_fixed_10u_array_ap_fixed_16_6_5_3_0_10u_relu_config10_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal io_acc_block_signal_op3 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_res_V_data_0_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_1_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_2_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_3_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_4_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_5_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_6_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_7_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_8_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_res_V_data_9_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal data_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal data_V_data_1_V_blk_n : STD_LOGIC;
    signal data_V_data_2_V_blk_n : STD_LOGIC;
    signal data_V_data_3_V_blk_n : STD_LOGIC;
    signal data_V_data_4_V_blk_n : STD_LOGIC;
    signal data_V_data_5_V_blk_n : STD_LOGIC;
    signal data_V_data_6_V_blk_n : STD_LOGIC;
    signal data_V_data_7_V_blk_n : STD_LOGIC;
    signal data_V_data_8_V_blk_n : STD_LOGIC;
    signal data_V_data_9_V_blk_n : STD_LOGIC;
    signal res_V_data_0_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_1_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_2_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_3_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_4_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_5_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_6_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_7_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_8_V_TDATA_blk_n : STD_LOGIC;
    signal res_V_data_9_V_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln1494_fu_294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_1_fu_300_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_2_fu_306_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_3_fu_312_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_4_fu_318_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_5_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_6_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_7_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_8_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln1494_9_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0_0to0 : STD_LOGIC;
    signal ap_reset_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal res_V_data_0_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_0_V_TVALID_int : STD_LOGIC;
    signal res_V_data_0_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_0_V_U_vld_out : STD_LOGIC;
    signal res_V_data_1_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_1_V_TVALID_int : STD_LOGIC;
    signal res_V_data_1_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_1_V_U_vld_out : STD_LOGIC;
    signal res_V_data_2_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_2_V_TVALID_int : STD_LOGIC;
    signal res_V_data_2_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_2_V_U_vld_out : STD_LOGIC;
    signal res_V_data_3_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_3_V_TVALID_int : STD_LOGIC;
    signal res_V_data_3_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_3_V_U_vld_out : STD_LOGIC;
    signal res_V_data_4_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_4_V_TVALID_int : STD_LOGIC;
    signal res_V_data_4_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_4_V_U_vld_out : STD_LOGIC;
    signal res_V_data_5_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_5_V_TVALID_int : STD_LOGIC;
    signal res_V_data_5_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_5_V_U_vld_out : STD_LOGIC;
    signal res_V_data_6_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_6_V_TVALID_int : STD_LOGIC;
    signal res_V_data_6_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_6_V_U_vld_out : STD_LOGIC;
    signal res_V_data_7_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_7_V_TVALID_int : STD_LOGIC;
    signal res_V_data_7_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_7_V_U_vld_out : STD_LOGIC;
    signal res_V_data_8_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_8_V_TVALID_int : STD_LOGIC;
    signal res_V_data_8_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_8_V_U_vld_out : STD_LOGIC;
    signal res_V_data_9_V_TDATA_int : STD_LOGIC_VECTOR (15 downto 0);
    signal res_V_data_9_V_TVALID_int : STD_LOGIC;
    signal res_V_data_9_V_TREADY_int : STD_LOGIC;
    signal regslice_both_res_V_data_9_V_U_vld_out : STD_LOGIC;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_res_V_data_0_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_0_V_TDATA_int,
        vld_in => res_V_data_0_V_TVALID_int,
        ack_in => res_V_data_0_V_TREADY_int,
        data_out => res_V_data_0_V_TDATA,
        vld_out => regslice_both_res_V_data_0_V_U_vld_out,
        ack_out => res_V_data_0_V_TREADY,
        apdone_blk => regslice_both_res_V_data_0_V_U_apdone_blk);

    regslice_both_res_V_data_1_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_1_V_TDATA_int,
        vld_in => res_V_data_1_V_TVALID_int,
        ack_in => res_V_data_1_V_TREADY_int,
        data_out => res_V_data_1_V_TDATA,
        vld_out => regslice_both_res_V_data_1_V_U_vld_out,
        ack_out => res_V_data_1_V_TREADY,
        apdone_blk => regslice_both_res_V_data_1_V_U_apdone_blk);

    regslice_both_res_V_data_2_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_2_V_TDATA_int,
        vld_in => res_V_data_2_V_TVALID_int,
        ack_in => res_V_data_2_V_TREADY_int,
        data_out => res_V_data_2_V_TDATA,
        vld_out => regslice_both_res_V_data_2_V_U_vld_out,
        ack_out => res_V_data_2_V_TREADY,
        apdone_blk => regslice_both_res_V_data_2_V_U_apdone_blk);

    regslice_both_res_V_data_3_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_3_V_TDATA_int,
        vld_in => res_V_data_3_V_TVALID_int,
        ack_in => res_V_data_3_V_TREADY_int,
        data_out => res_V_data_3_V_TDATA,
        vld_out => regslice_both_res_V_data_3_V_U_vld_out,
        ack_out => res_V_data_3_V_TREADY,
        apdone_blk => regslice_both_res_V_data_3_V_U_apdone_blk);

    regslice_both_res_V_data_4_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_4_V_TDATA_int,
        vld_in => res_V_data_4_V_TVALID_int,
        ack_in => res_V_data_4_V_TREADY_int,
        data_out => res_V_data_4_V_TDATA,
        vld_out => regslice_both_res_V_data_4_V_U_vld_out,
        ack_out => res_V_data_4_V_TREADY,
        apdone_blk => regslice_both_res_V_data_4_V_U_apdone_blk);

    regslice_both_res_V_data_5_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_5_V_TDATA_int,
        vld_in => res_V_data_5_V_TVALID_int,
        ack_in => res_V_data_5_V_TREADY_int,
        data_out => res_V_data_5_V_TDATA,
        vld_out => regslice_both_res_V_data_5_V_U_vld_out,
        ack_out => res_V_data_5_V_TREADY,
        apdone_blk => regslice_both_res_V_data_5_V_U_apdone_blk);

    regslice_both_res_V_data_6_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_6_V_TDATA_int,
        vld_in => res_V_data_6_V_TVALID_int,
        ack_in => res_V_data_6_V_TREADY_int,
        data_out => res_V_data_6_V_TDATA,
        vld_out => regslice_both_res_V_data_6_V_U_vld_out,
        ack_out => res_V_data_6_V_TREADY,
        apdone_blk => regslice_both_res_V_data_6_V_U_apdone_blk);

    regslice_both_res_V_data_7_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_7_V_TDATA_int,
        vld_in => res_V_data_7_V_TVALID_int,
        ack_in => res_V_data_7_V_TREADY_int,
        data_out => res_V_data_7_V_TDATA,
        vld_out => regslice_both_res_V_data_7_V_U_vld_out,
        ack_out => res_V_data_7_V_TREADY,
        apdone_blk => regslice_both_res_V_data_7_V_U_apdone_blk);

    regslice_both_res_V_data_8_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_8_V_TDATA_int,
        vld_in => res_V_data_8_V_TVALID_int,
        ack_in => res_V_data_8_V_TREADY_int,
        data_out => res_V_data_8_V_TDATA,
        vld_out => regslice_both_res_V_data_8_V_U_vld_out,
        ack_out => res_V_data_8_V_TREADY,
        apdone_blk => regslice_both_res_V_data_8_V_U_apdone_blk);

    regslice_both_res_V_data_9_V_U : component regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => res_V_data_9_V_TDATA_int,
        vld_in => res_V_data_9_V_TVALID_int,
        ack_in => res_V_data_9_V_TREADY_int,
        data_out => res_V_data_9_V_TDATA,
        vld_out => regslice_both_res_V_data_9_V_U_vld_out,
        ack_out => res_V_data_9_V_TREADY,
        apdone_blk => regslice_both_res_V_data_9_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_block_pp0_stage0_subdone, ap_reset_idle_pp0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op3, regslice_both_res_V_data_0_V_U_apdone_blk, regslice_both_res_V_data_1_V_U_apdone_blk, regslice_both_res_V_data_2_V_U_apdone_blk, regslice_both_res_V_data_3_V_U_apdone_blk, regslice_both_res_V_data_4_V_U_apdone_blk, regslice_both_res_V_data_5_V_U_apdone_blk, regslice_both_res_V_data_6_V_U_apdone_blk, regslice_both_res_V_data_7_V_U_apdone_blk, regslice_both_res_V_data_8_V_U_apdone_blk, regslice_both_res_V_data_9_V_U_apdone_blk)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((io_acc_block_signal_op3 = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((regslice_both_res_V_data_5_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_4_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_3_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_2_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_1_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_0_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_9_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_8_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_7_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_6_V_U_apdone_blk = ap_const_logic_1))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op3, regslice_both_res_V_data_0_V_U_apdone_blk, regslice_both_res_V_data_1_V_U_apdone_blk, regslice_both_res_V_data_2_V_U_apdone_blk, regslice_both_res_V_data_3_V_U_apdone_blk, regslice_both_res_V_data_4_V_U_apdone_blk, regslice_both_res_V_data_5_V_U_apdone_blk, regslice_both_res_V_data_6_V_U_apdone_blk, regslice_both_res_V_data_7_V_U_apdone_blk, regslice_both_res_V_data_8_V_U_apdone_blk, regslice_both_res_V_data_9_V_U_apdone_blk, res_V_data_0_V_TREADY_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((io_acc_block_signal_op3 = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (res_V_data_0_V_TREADY_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((res_V_data_0_V_TREADY_int = ap_const_logic_0) or (regslice_both_res_V_data_5_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_4_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_3_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_2_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_1_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_0_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_9_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_8_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_7_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_6_V_U_apdone_blk = ap_const_logic_1))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_start, ap_done_reg, ap_enable_reg_pp0_iter1, io_acc_block_signal_op3, regslice_both_res_V_data_0_V_U_apdone_blk, regslice_both_res_V_data_1_V_U_apdone_blk, regslice_both_res_V_data_2_V_U_apdone_blk, regslice_both_res_V_data_3_V_U_apdone_blk, regslice_both_res_V_data_4_V_U_apdone_blk, regslice_both_res_V_data_5_V_U_apdone_blk, regslice_both_res_V_data_6_V_U_apdone_blk, regslice_both_res_V_data_7_V_U_apdone_blk, regslice_both_res_V_data_8_V_U_apdone_blk, regslice_both_res_V_data_9_V_U_apdone_blk, res_V_data_0_V_TREADY_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_start = ap_const_logic_1) and ((io_acc_block_signal_op3 = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (res_V_data_0_V_TREADY_int = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((res_V_data_0_V_TREADY_int = ap_const_logic_0) or (regslice_both_res_V_data_5_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_4_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_3_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_2_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_1_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_0_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_9_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_8_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_7_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_6_V_U_apdone_blk = ap_const_logic_1))));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg, io_acc_block_signal_op3)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((io_acc_block_signal_op3 = ap_const_logic_0) or (ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(regslice_both_res_V_data_0_V_U_apdone_blk, regslice_both_res_V_data_1_V_U_apdone_blk, regslice_both_res_V_data_2_V_U_apdone_blk, regslice_both_res_V_data_3_V_U_apdone_blk, regslice_both_res_V_data_4_V_U_apdone_blk, regslice_both_res_V_data_5_V_U_apdone_blk, regslice_both_res_V_data_6_V_U_apdone_blk, regslice_both_res_V_data_7_V_U_apdone_blk, regslice_both_res_V_data_8_V_U_apdone_blk, regslice_both_res_V_data_9_V_U_apdone_blk)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((regslice_both_res_V_data_5_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_4_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_3_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_2_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_1_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_0_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_9_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_8_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_7_V_U_apdone_blk = ap_const_logic_1) or (regslice_both_res_V_data_6_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start;

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_idle_pp0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_0to0_assign_proc : process(ap_enable_reg_pp0_iter0)
    begin
        if ((ap_enable_reg_pp0_iter0 = ap_const_logic_0)) then 
            ap_idle_pp0_0to0 <= ap_const_logic_1;
        else 
            ap_idle_pp0_0to0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_reset_idle_pp0_assign_proc : process(ap_start, ap_idle_pp0_0to0)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_idle_pp0_0to0 = ap_const_logic_1))) then 
            ap_reset_idle_pp0 <= ap_const_logic_1;
        else 
            ap_reset_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_0_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_0_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_0_V_blk_n <= data_V_data_0_V_empty_n;
        else 
            data_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_0_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_0_V_read <= ap_const_logic_1;
        else 
            data_V_data_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_1_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_1_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_1_V_blk_n <= data_V_data_1_V_empty_n;
        else 
            data_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_1_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_1_V_read <= ap_const_logic_1;
        else 
            data_V_data_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_2_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_2_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_2_V_blk_n <= data_V_data_2_V_empty_n;
        else 
            data_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_2_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_2_V_read <= ap_const_logic_1;
        else 
            data_V_data_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_3_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_3_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_3_V_blk_n <= data_V_data_3_V_empty_n;
        else 
            data_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_3_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_3_V_read <= ap_const_logic_1;
        else 
            data_V_data_3_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_4_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_4_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_4_V_blk_n <= data_V_data_4_V_empty_n;
        else 
            data_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_4_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_4_V_read <= ap_const_logic_1;
        else 
            data_V_data_4_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_5_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_5_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_5_V_blk_n <= data_V_data_5_V_empty_n;
        else 
            data_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_5_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_5_V_read <= ap_const_logic_1;
        else 
            data_V_data_5_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_6_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_6_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_6_V_blk_n <= data_V_data_6_V_empty_n;
        else 
            data_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_6_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_6_V_read <= ap_const_logic_1;
        else 
            data_V_data_6_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_7_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_7_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_7_V_blk_n <= data_V_data_7_V_empty_n;
        else 
            data_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_7_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_7_V_read <= ap_const_logic_1;
        else 
            data_V_data_7_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_8_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_8_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_8_V_blk_n <= data_V_data_8_V_empty_n;
        else 
            data_V_data_8_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_8_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_8_V_read <= ap_const_logic_1;
        else 
            data_V_data_8_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_V_data_9_V_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, data_V_data_9_V_empty_n, ap_block_pp0_stage0)
    begin
        if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_V_data_9_V_blk_n <= data_V_data_9_V_empty_n;
        else 
            data_V_data_9_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_V_data_9_V_read_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_V_data_9_V_read <= ap_const_logic_1;
        else 
            data_V_data_9_V_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln1494_1_fu_300_p2 <= "1" when (signed(data_V_data_1_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_2_fu_306_p2 <= "1" when (signed(data_V_data_2_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_3_fu_312_p2 <= "1" when (signed(data_V_data_3_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_4_fu_318_p2 <= "1" when (signed(data_V_data_4_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_5_fu_324_p2 <= "1" when (signed(data_V_data_5_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_6_fu_330_p2 <= "1" when (signed(data_V_data_6_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_7_fu_336_p2 <= "1" when (signed(data_V_data_7_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_8_fu_342_p2 <= "1" when (signed(data_V_data_8_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_9_fu_348_p2 <= "1" when (signed(data_V_data_9_V_dout) > signed(ap_const_lv16_0)) else "0";
    icmp_ln1494_fu_294_p2 <= "1" when (signed(data_V_data_0_V_dout) > signed(ap_const_lv16_0)) else "0";
    io_acc_block_signal_op3 <= (data_V_data_9_V_empty_n and data_V_data_8_V_empty_n and data_V_data_7_V_empty_n and data_V_data_6_V_empty_n and data_V_data_5_V_empty_n and data_V_data_4_V_empty_n and data_V_data_3_V_empty_n and data_V_data_2_V_empty_n and data_V_data_1_V_empty_n and data_V_data_0_V_empty_n);

    res_V_data_0_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_0_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_0_V_TDATA_blk_n <= res_V_data_0_V_TREADY_int;
        else 
            res_V_data_0_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_0_V_TDATA_int <= 
        data_V_data_0_V_dout when (icmp_ln1494_fu_294_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_0_V_TVALID <= regslice_both_res_V_data_0_V_U_vld_out;

    res_V_data_0_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_0_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_0_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_1_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_1_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_1_V_TDATA_blk_n <= res_V_data_1_V_TREADY_int;
        else 
            res_V_data_1_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_1_V_TDATA_int <= 
        data_V_data_1_V_dout when (icmp_ln1494_1_fu_300_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_1_V_TVALID <= regslice_both_res_V_data_1_V_U_vld_out;

    res_V_data_1_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_1_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_1_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_2_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_2_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_2_V_TDATA_blk_n <= res_V_data_2_V_TREADY_int;
        else 
            res_V_data_2_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_2_V_TDATA_int <= 
        data_V_data_2_V_dout when (icmp_ln1494_2_fu_306_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_2_V_TVALID <= regslice_both_res_V_data_2_V_U_vld_out;

    res_V_data_2_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_2_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_2_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_3_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_3_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_3_V_TDATA_blk_n <= res_V_data_3_V_TREADY_int;
        else 
            res_V_data_3_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_3_V_TDATA_int <= 
        data_V_data_3_V_dout when (icmp_ln1494_3_fu_312_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_3_V_TVALID <= regslice_both_res_V_data_3_V_U_vld_out;

    res_V_data_3_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_3_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_3_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_4_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_4_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_4_V_TDATA_blk_n <= res_V_data_4_V_TREADY_int;
        else 
            res_V_data_4_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_4_V_TDATA_int <= 
        data_V_data_4_V_dout when (icmp_ln1494_4_fu_318_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_4_V_TVALID <= regslice_both_res_V_data_4_V_U_vld_out;

    res_V_data_4_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_4_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_4_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_5_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_5_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_5_V_TDATA_blk_n <= res_V_data_5_V_TREADY_int;
        else 
            res_V_data_5_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_5_V_TDATA_int <= 
        data_V_data_5_V_dout when (icmp_ln1494_5_fu_324_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_5_V_TVALID <= regslice_both_res_V_data_5_V_U_vld_out;

    res_V_data_5_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_5_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_5_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_6_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_6_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_6_V_TDATA_blk_n <= res_V_data_6_V_TREADY_int;
        else 
            res_V_data_6_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_6_V_TDATA_int <= 
        data_V_data_6_V_dout when (icmp_ln1494_6_fu_330_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_6_V_TVALID <= regslice_both_res_V_data_6_V_U_vld_out;

    res_V_data_6_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_6_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_6_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_7_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_7_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_7_V_TDATA_blk_n <= res_V_data_7_V_TREADY_int;
        else 
            res_V_data_7_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_7_V_TDATA_int <= 
        data_V_data_7_V_dout when (icmp_ln1494_7_fu_336_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_7_V_TVALID <= regslice_both_res_V_data_7_V_U_vld_out;

    res_V_data_7_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_7_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_7_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_8_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_8_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_8_V_TDATA_blk_n <= res_V_data_8_V_TREADY_int;
        else 
            res_V_data_8_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_8_V_TDATA_int <= 
        data_V_data_8_V_dout when (icmp_ln1494_8_fu_342_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_8_V_TVALID <= regslice_both_res_V_data_8_V_U_vld_out;

    res_V_data_8_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_8_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_8_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;


    res_V_data_9_V_TDATA_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, res_V_data_9_V_TREADY_int)
    begin
        if (((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0)))) then 
            res_V_data_9_V_TDATA_blk_n <= res_V_data_9_V_TREADY_int;
        else 
            res_V_data_9_V_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_V_data_9_V_TDATA_int <= 
        data_V_data_9_V_dout when (icmp_ln1494_9_fu_348_p2(0) = '1') else 
        ap_const_lv16_0;
    res_V_data_9_V_TVALID <= regslice_both_res_V_data_9_V_U_vld_out;

    res_V_data_9_V_TVALID_int_assign_proc : process(ap_start, ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            res_V_data_9_V_TVALID_int <= ap_const_logic_1;
        else 
            res_V_data_9_V_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

end behav;
